name: faceapp
description: "A new Flutter project."
publish_to: "none"
version: 1.0.5+7
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  image: ^4.1.3
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_native_splash: ^2.3.7
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  path_provider: ^2.1.1
  camera: ^0.10.5+7
  image_picker: ^1.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_statusbarcolor_ns: ^0.5.0
  dotted_border: ^2.1.0
  pinput: ^3.0.1
  shared_preferences: ^2.2.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0
  firebase_core: ^2.24.2
  url_launcher: ^6.2.2
  synchronized: ^3.1.0+1
  page_transition: ^2.1.0
  fluttertoast: ^8.2.4
  flutter_keyboard_visibility: ^6.0.0
  flutter_image_compress: ^2.1.0
  recaptcha_enterprise_flutter: ^18.4.2
  package_info_plus: ^5.0.1
  phone_numbers_parser: ^8.1.0
  country_code_picker:
    git:
      url: https://github.com/Kiriharan01/CountryCodePicker.git
      ref: feature/remove_country
  baseflow_plugin_template: ^2.1.2
  permission_handler: ^10.2.0
  connectivity_plus: ^5.0.2
  multi_dropdown: ^2.1.4
  flutter_awesome_select: ^6.5.0
  sticky_headers: ^0.3.0+2
  tutorial_coach_mark:
    git:
      url: https://github.com/Kiriharan01/tutorial_coach_mark
      ref: feature/text_update

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi/Fonts/Satoshi-Regular.ttf
        - asset: assets/fonts/Satoshi/Fonts/Satoshi-Bold.ttf
        - asset: assets/fonts/Satoshi/Fonts/Satoshi-Medium.ttf

flutter_native_splash:
  background_image: "assets/images/background_logo.png"
  # background_image_ios: "assets/images/background.png"
  # image: "assets/images/center_logo.png"
  # image_ios: "assets/images/center_logo.png"
  # branding: "assets/images/bottom_logo.png"
  # branding_ios: "assets/images/bottom_logo.png"
  # branding_mode: bottom

  android_12:
    background_image: "assets/images/background_logo.png"
    image: assets/images/center_logo_12.png
    branding: assets/images/imageedit_2.png
    color: "#00031B"

  android_gravity: fill
  android: true
  ios: false
  web: false
